#lang racket

(define (make-account balance init-password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "Недостаточно денег на счете"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (incorrect-password . args)
    "Неверный пароль")
  (define (check-password password)
    (eq? password init-password))
  (define (dispatch password m)
    (if (eq? password init-password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              ((eq? m 'check) check-password)
              (else (error "Неизвестный вызов -- MAKE-ACCOUNT" m)))
        incorrect-password))
  dispatch)


(define Sasha-Acccount (make-account 100 "password"))
;((Sasha-Acccount "password" 'withdraw) 25)
;((Sasha-Acccount "password" 'withdraw) 125)
;((Sasha-Acccount "incorrect" 'withdraw) 25)

(define (make-join account password new-password)
  (define (incorrect-password . args)
    "Неверный пароль!")
  (if ((account password 'check) password)
      (lambda (proxi-password command)
        (if (or (eq? proxi-password new-password) (eq? proxi-password password))
            (account password command)
            incorrect-password))
      incorrect-password))

  
(define Anna-Account (make-join Sasha-Acccount "password" "Anna's passowrd"))
((Anna-Account "password" 'withdraw) 25)
((Anna-Account "Anna's passowrd" 'withdraw) 25)
((Anna-Account "incorrect" 'withdraw) 25)